'\"
'\"	@(#)viewdict.8	1.1 5/18/89 (cc.utexas.edu) /home/emx/u2/cc/clyde/src/new/passwd/checkpasswd/dict/SCCS/s.viewdict.8
'\"
.TH VIEWDICT 1
.SH NAME
viewdict \- View DBM dictionary
.SH SYNOPSIS
.B viewdict
dbm_dictionary
.SH DESCRIPTION
.I Viewdict
reads a dictionary data base and prints its contents to the standard
output.
.SH SEE ALSO
makedict
